__default__:
    partition: "wrighton-hi,wrighton-low"
    time: 14-00:00:00
    nodes: 1
    ntasks: 20
    mail-type: FAIL
    mail-user: "ileleiwi@colostate.edu"
    mem: "200gb"
    job-name: snakemake_bin_wkflw
    output: "./logs_slurm/{rule}.{wildcards}.out" #-e and -o flag
